---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/language: java
  name: tanzu-java-web-app
  namespace: dev
spec:
  params:
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: java
  - name: scanning_source_policy
    value: lax-scan-policy
  - name: scanning_image_policy
    value: lax-scan-policy
  - name: gitops_repository_owner
    value: "asdf"
  - name: deliverable_repository_owner
    value: "asdf"
  - name: deliverable_branch
    value: "main"
  - name: deliverable_repository_name
    value: "deliverable-config"
  - name: gitops_repository_name
    value: "gitops-tap"
  - name: gitops_branch
    value: main
  source:
    git:
      ref:
        branch: dev
      url: https://github.com/BeepBoopRobit/ugh.git