---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/language: java
  name: tanzu-java-web-app
  namespace: dev
spec:
  params:
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: java
  source:
    git:
      ref:
        branch: dev
        #url: ssh://git@gitlab.snugl.io/asdf/tanzu-java-web-app.git
      url: https://gitlab.snugl.io/asdf/tanzu-java-web-app.git